title: Food & Wealth
description: ''
author: 'Icíar Lloréns Jover, Yassine Zouaghi and Guillaume Vizier'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:

excerpt_separator: <!-- more -->
